### PR TITLE
Remove cljx

### PR DESCRIPTION
**Pull request by iku000888**
### Why?

I would like to interactively develop om-tools as a local checkout in my project at work and cljx is problematic for this.

### Solution?

Use reader conditionals by migrating to cljc

### Consequences

- Minimum clojure version 1.7
- But as a Consequence of cljs version mentioned below, 1.8

### cljs and om version

Same as the one I use at work. I think nobody has the bandwidth to support old versions.

### TODO
- [x] drop tests for old om versions
- [x] drop cljx
- [x] check that it works in the project I work on
- [x] check that the examples are functional
- [ ] make the tests pass, or
- [ ] skpi the tests for now

### CODE REVIEW

**Comment by loganlinn** [comment]
Oh it looks like the tests are failing. Let’s get those fixed up

**Comment by iku000888** [comment]
@loganlinn 

Sorry for the churn!
My effort budget ran out on trying to make the cljs tests pass.

In the interest of moving forward, I propose to stash the tests as I am guessing that the tests fail because they rely on react internals and react-addons, which also need to be upgraded along with om. 

If you do have some bandwidth to check the cljs tests and have some tricks to move forward that would be best, but otherwise I will use the example apps and the project at work as a Q.A. platform in the meanwhile.

What do you think?

**Comment by iku000888** [comment]
@loganlinn 

So I fixed the tests sufficiently that I can run most of the tests in the browser. Commented out the tests that are problematic.

image

I am seeing that phantomjs is timing out on travis, so I am more confident that we should consider letting it go...

I think this is a happy middle ground as a merge point, so yeah let me know what you think...

**Comment by iku000888** [comment]
@loganlinn Would be awesome if I could ship this to so I can start work on catching up against latest om/react (and then fixing the tests), so if there is anything else I can do, just let me know :pray: 

Thanks for your time :bowing_man:

**Comment by iku000888** [comment]
@loganlinn Thanks for the understanding! :pray: 

Next goal for me is to do the catch up work with recent om/react :muscle: 

@w01fe If you could push a release so I could put this into battle at work that would be awesome ;)
No rush tho.

**Comment by loganlinn** [comment]
@iku000888 I've released 0.5.0 to clojars: https://clojars.org/prismatic/om-tools/versions/0.5.0

**Comment by iku000888** [comment]
thanks!

**Pull request merged**
